m4_include([ac_create_stdint_h.m4])
m4_include([ac_ptyranges.m4])
m4_include([ac_compile_check_sizeof.m4])
m4_include([ac_check_win32.m4])
m4_include([ac_shipped_lib.m4])
m4_include([acx_pthread.m4])
m4_include([ac_decl_or_zero.m4])
m4_include([ac_sco.m4])
